

development:
  adapter: postgresql
  database: ndd_dev1
  username: test_usr_dev1
  password:  test_usr_dev1
  host: localhost
  port: 5432 


test:
  adapter: postgresql
  database: ndd_test1
  username: test_usr_dev1
  password:  test_usr_dev1
  host: localhost
  port: 5432 

production:
  adapter: postgresql
  database: ndd_dev1
  username: test_usr_dev1
  password:  test_usr_dev1
  host: localhost
  port: 5432 
